#include<iostream>              //Header Lines...
using namespace std;

int main()                  //Function...
{
    

    //Write your Code here...
    //Follow this Structure for C++ Programs...

    return 0;                   //End of Programming...

}